# Generated by Django 3.0.10 on 2021-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='status',
            field=models.CharField(blank=True, choices=[('febrile', 'febrile'), ('critical', 'critical'), ('recovery', 'recovery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('febrile', 'febrile'), ('critical', 'critical'), ('recovery', 'recovery')], max_length=20, null=True),
        ),
    ]
